Added lib_path file to manage library paths.

diff --git a/PnR/run_PnR b/PnR/run_PnR
--- a/PnR/run_PnR
+++ b/PnR/run_PnR
@@ -4,6 +4,20 @@
 
 echo "Innovus Plance & Route Control Script"
 
+# read cap_table, target_library and library_search_path from ../lib/lib_path
+target_library=$(grep '^target_library=' ../lib/lib_path | cut -d'=' -f2)
+library_search_path=$(grep '^library_search_path=' ../lib/lib_path | cut -d'=' -f2)
+cap_table=$(grep '^cap_table=' ../lib/lib_path | cut -d'=' -f2)
+clockBufName=$(grep '^clockBufName=' ../lib/lib_path | cut -d'=' -f2)
+fillerCells=$(grep '^fillerCells=' ../lib/lib_path | cut -d'=' -f2)
+lef=$(grep '^lef=' ../lib/lib_path | cut -d'=' -f2)
+if [ -z "$target_library" ] echo "Error: target_library not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$library_search_path" ] echo "Error: library_search_path not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$cap_table" ] echo "Error: cap_table not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$clockBufName" ] echo "Error: clockBufName not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$fillerCells" ] echo "Error: fillerCells not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$lef" ] echo "Error: lef not found in ../lib/lib_path." ; exit 1; fi
+
 # reset control variables
 gui=0
 topmodule=""
@@ -34,8 +48,8 @@ pushd work
 cat > ../scripts/Default.view <<EOF
 # Version:1.0 MMMC View Definition File
 # Do Not Remove Above Line
-create_rc_corner -name rc -cap_table {../../lib/sky130_cap.captable} -preRoute_res {1.0} -preRoute_cap {1.0} -preRoute_clkres {0.0} -preRoute_clkcap {0.0} -postRoute_res {1.0} -postRoute_cap {1.0} -postRoute_xcap {1.0} -postRoute_clkres {0.0} -postRoute_clkcap {0.0}
-create_library_set -name libSTD -timing {../../lib/scs130lp_tt_1.62_25_nldm.lib}
+create_rc_corner -name rc -cap_table {${cap_table}} -preRoute_res {1.0} -preRoute_cap {1.0} -preRoute_clkres {0.0} -preRoute_clkcap {0.0} -postRoute_res {1.0} -postRoute_cap {1.0} -postRoute_xcap {1.0} -postRoute_clkres {0.0} -postRoute_clkcap {0.0}
+create_library_set -name libSTD -timing {${library_search_path}/${target_library}.lib}
 create_constraint_mode -name Constraints -sdc_files {../../synthesis/work/output/${topmodule}_syn.sdc}
 create_delay_corner -name Delay -library_set {libSTD} -rc_corner {rc}
 create_analysis_view -name Default -constraint_mode {Constraints} -delay_corner {Delay}
@@ -46,14 +60,14 @@ if [ $gui == 1 ]
 then
    if [ $top == 1 ]
    then
-      innovus -execute "win; set BASENAME $topmodule;" -files ../scripts/top-level.tcl -log ../work/log/run.log -cmd ../work/log/run.cmd -overwrite
+      innovus -execute "win; set BASENAME $topmodule; set init_lef_file ${lef}; set fillerCells [list ${fillerCells}]; set clockBufName ${clockBufName}" -files ../scripts/top-level.tcl -log ../work/log/run.log -cmd ../work/log/run.cmd -overwrite
    else
       innovus
    fi
 else
    if [ $top == 1 ]
    then
-      innovus -execute "win; set BASENAME $topmodule;" -files ../scripts/top-level.tcl -log ../work/log/run.log -cmd ../work/log/run.cmd -overwrite -nowin
+      innovus -execute "set BASENAME $topmodule; set init_lef_file ${lef} set fillerCells [list ${fillerCells}]; set clockBufName ${clockBufName}" -files ../scripts/top-level.tcl -log ../work/log/run.log -cmd ../work/log/run.cmd -overwrite -nowin
    else
       innovus -nowin
    fi
diff --git a/simulation/run_sim b/simulation/run_sim
--- a/simulation/run_sim
+++ b/simulation/run_sim
@@ -4,10 +4,15 @@
 
 echo "**********Xcelcium Simulation Control File**********"
 
+# Read stdcell_verilog variable from ../lib/lib_path file
+stdcell_verilog=$(grep '^stdcell_verilog=' ../lib/lib_path | cut -d'=' -f2)
+if [ -z "$stdcell_verilog" ] echo "Error: stdcell_verilog not found in ../lib/lib_path." ; exit 1 ; fi
+
 # reset control variables
 clean=0
 compile=0
 cells=0
+layout=0
 sim=0
 gui=0
 waveform=0
@@ -30,6 +35,9 @@ do
     elif [ "$arg" == "-cells" ]
     then
 	    cells=1
+    elif [ "$arg" == "-layout" ]
+    then
+        layout=1
     elif [ "$arg" == "-gui" ]
     then
 	    gui=1
@@ -60,13 +68,19 @@ then
     # remove old compile results
     if [ $cells == 1 ]
     then
-    echo "**********Compiling source files and standard cells, and generating sdf.cmd**********"
-        xmverilog /dept/enee/software/tsmc_65/TSMC_IP/standard_cell_65GP/tcbn65gplus_200a/FE/TSMCHOME/digital/Front_End/verilog/tcbn65gplus_200a/tcbn65gplus.v ../../synthesis/work/output/${topmodule}_syn.v -clean -compile
-        bash ../script/sdf_cmd_generate "$topmodule"
+        echo "**********Compiling source files and standard cells, and generating sdf.cmd**********"
+        xmverilog ${stdcell_verilog} ../../synthesis/work/output/${topmodule}_syn.v -clean -compile
+        bash ../script/sdf_cmd_generate_syn "$topmodule"
         xmsdfc ../../synthesis/work/output/${topmodule}_syn.sdf
+    elif [ $layout == 1 ]
+    then
+        echo "**********Compiling source files and standard cells, and generating sdf.cmd**********"
+        xmverilog ${stdcell_verilog} ../../PnR/work/output/${topmodule}_pnr.v -clean -compile
+        bash ../script/sdf_cmd_generate_pnr "$topmodule"
+        xmsdfc ../../PnR/work/output/${topmodule}_pnr.sdf
     else
-        xmverilog ../../source/*.v -clean -compile
-    fi 
+        xmverilog ${stdcell_verilog} ../../source/*.v -clean -compile
+    fi  
 fi
 
 # if simulating files
@@ -75,15 +89,15 @@ then
     echo "**********Starting simulation**********"
     if [ $gui == 1 ]
     then
-        if [ $cells == 1 ]
+        if [ $cells == 1 ] || [ $layout == 1 ]
         then
-        xmverilog ../testbench/tb_${topmodule}.v -access +rw -mess +gui	-sdf_cmd_file ../sdf/sdf.cmd -dumptiming timingdump.log -timescale 1ns/1ps
+            xmverilog ../testbench/tb_${topmodule}.v -access +rw -mess +gui	-sdf_cmd_file ../sdf/sdf.cmd -dumptiming timingdump.log -timescale 1ns/1ps
         else
-        xmverilog ../testbench/tb_${topmodule}.v -access +rw -mess +gui -dumptiming timingdump.log -timescale 1ns/1ps
+            xmverilog ../testbench/tb_${topmodule}.v -access +rw -mess +gui -dumptiming timingdump.log -timescale 1ns/1ps
         fi
 	# if gui
     else
-    if [ $cells == 1 ]
+    if [ $cells == 1 ] || [ $layout == 1 ]
         then
         xmverilog ../testbench/tb_${topmodule}.v -access +rw -mess	-sdf_cmd_file ../sdf/sdf.cmd -dumptiming timingdump.log -timescale 1ns/1ps
         else
diff --git a/synthesis/run_syn b/synthesis/run_syn
--- a/synthesis/run_syn
+++ b/synthesis/run_syn
@@ -4,6 +4,16 @@
 
 echo "Genus Synthesis Control Script"
 
+# Read target_library and target_library_path from ../lib/lib_path
+target_library=$(grep '^target_library=' ../lib/lib_path | cut -d'=' -f2)
+library_search_path=$(grep '^library_search_path=' ../lib/lib_path | cut -d'=' -f2)
+
+if [ -z "$target_library" ] echo "Error: target_library not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$library_search_path" ] echo "Error: library_search_path not found in ../lib/lib_path." ; exit 1 ; fi
+
+echo "target_library: $target_library"
+echo "library_search_path: $target_library_path"
+
 # reset control variables
 gui=0
 topmodule=""
@@ -35,14 +45,14 @@ if [ $gui == 1 ]
 then
    if [ $top == 1 ]
    then
-      genus -execute "set top_module $topmodule" -f ../scripts/synthesis.tcl -gui
+      genus -execute "set target_library $target_library; set init_lib_search_path $library_search_path; set top_module $topmodule" -f ../scripts/synthesis.tcl -gui
    else
       genus -gui
    fi
 else
    if [ $top == 1 ]
    then
-      genus -execute "set top_module $topmodule" -f ../scripts/synthesis.tcl 
+      genus -execute "set target_library $target_library; set init_lib_search_path $library_search_path; set top_module $topmodulee" -f ../scripts/synthesis.tcl 
    else
       genus
    fi
