Fixed subtle bugs.

diff --git a/PnR/run_PnR b/PnR/run_PnR
--- a/PnR/run_PnR
+++ b/PnR/run_PnR
@@ -11,12 +11,12 @@ cap_table=$(grep '^cap_table=' ../lib/lib_path | cut -d'=' -f2)
 clockBufName=$(grep '^clockBufName=' ../lib/lib_path | cut -d'=' -f2)
 fillerCells=$(grep '^fillerCells=' ../lib/lib_path | cut -d'=' -f2)
 lef=$(grep '^lef=' ../lib/lib_path | cut -d'=' -f2)
-if [ -z "$target_library" ] echo "Error: target_library not found in ../lib/lib_path." ; exit 1 ; fi
-if [ -z "$library_search_path" ] echo "Error: library_search_path not found in ../lib/lib_path." ; exit 1 ; fi
-if [ -z "$cap_table" ] echo "Error: cap_table not found in ../lib/lib_path." ; exit 1; fi
-if [ -z "$clockBufName" ] echo "Error: clockBufName not found in ../lib/lib_path." ; exit 1; fi
-if [ -z "$fillerCells" ] echo "Error: fillerCells not found in ../lib/lib_path." ; exit 1; fi
-if [ -z "$lef" ] echo "Error: lef not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$target_library" ]; then echo "Error: target_library not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$library_search_path" ]; then echo "Error: library_search_path not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$cap_table" ]; then echo "Error: cap_table not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$clockBufName" ]; then echo "Error: clockBufName not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$fillerCells" ]; then echo "Error: fillerCells not found in ../lib/lib_path." ; exit 1; fi
+if [ -z "$lef" ]; then echo "Error: lef not found in ../lib/lib_path." ; exit 1; fi
 
 # reset control variables
 gui=0
diff --git a/simulation/run_sim b/simulation/run_sim
--- a/simulation/run_sim
+++ b/simulation/run_sim
@@ -6,7 +6,11 @@ echo "**********Xcelcium Simulation Control File**********"
 
 # Read stdcell_verilog variable from ../lib/lib_path file
 stdcell_verilog=$(grep '^stdcell_verilog=' ../lib/lib_path | cut -d'=' -f2)
-if [ -z "$stdcell_verilog" ] echo "Error: stdcell_verilog not found in ../lib/lib_path." ; exit 1 ; fi
+if [ -z "$stdcell_verilog" ] 
+then 
+    echo "Error: stdcell_verilog not found in ../lib/lib_path."  
+    exit 1 
+fi
 
 # reset control variables
 clean=0
